import './globals.css'
import { Inter } from 'next/font/google'


export const metadata = {
  title: 'Tribbble',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
